// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWEHOeNgI3KXZ91JZN-wLa-JnKobmsVMQ',
    appId: '1:837932494635:web:16bfd7b2ef9c2f406a5f6e',
    messagingSenderId: '837932494635',
    projectId: 'ecmmerce-3bbd8',
    authDomain: 'ecmmerce-3bbd8.firebaseapp.com',
    storageBucket: 'ecmmerce-3bbd8.appspot.com',
    measurementId: 'G-TQENS9HRK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD23rACVqguwPRX421pqXz6mC6cXNaWv4',
    appId: '1:837932494635:android:b95f03dae5d5e2506a5f6e',
    messagingSenderId: '837932494635',
    projectId: 'ecmmerce-3bbd8',
    storageBucket: 'ecmmerce-3bbd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX0voHbzu7Wztku-sUqbLH4fiauFBe3lc',
    appId: '1:837932494635:ios:99ccaf7edef4569f6a5f6e',
    messagingSenderId: '837932494635',
    projectId: 'ecmmerce-3bbd8',
    storageBucket: 'ecmmerce-3bbd8.appspot.com',
    iosBundleId: 'com.example.ecommece',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX0voHbzu7Wztku-sUqbLH4fiauFBe3lc',
    appId: '1:837932494635:ios:99ccaf7edef4569f6a5f6e',
    messagingSenderId: '837932494635',
    projectId: 'ecmmerce-3bbd8',
    storageBucket: 'ecmmerce-3bbd8.appspot.com',
    iosBundleId: 'com.example.ecommece',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWEHOeNgI3KXZ91JZN-wLa-JnKobmsVMQ',
    appId: '1:837932494635:web:d4ce2603f55104166a5f6e',
    messagingSenderId: '837932494635',
    projectId: 'ecmmerce-3bbd8',
    authDomain: 'ecmmerce-3bbd8.firebaseapp.com',
    storageBucket: 'ecmmerce-3bbd8.appspot.com',
    measurementId: 'G-QSBWYVXGXN',
  );
}
